export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const INCREASE = "INCREASE";
export const DECREASE = "DECREASE";
export const CLEAR_CART = "CLEAR_CART"
export const CALCULATE_TOTALS = "CALCULATE_TOTALS";
export const CALCULATE_ITEM_SUBTOTALS = "CALCULATE_ITEM_SUBTOTALS";