export const INTITIAL_FETCH = "INTITIAL_FETCH";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const CALCULTATE_LENGTH = "CALCULTATE_LENGTH";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
